"""add inn verification

Revision ID: 0cf01b709de6
Revises: fb587027b0f4
Create Date: 2024-02-22 20:46:18.949671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf01b709de6'
down_revision: Union[str, None] = 'fb587027b0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('inn_verification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'inn_verification')
    # ### end Alembic commands ###
