"""delete username from user

Revision ID: 38638c2fd995
Revises: 94ef8270a05d
Create Date: 2024-02-18 22:03:25.622674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38638c2fd995'
down_revision: Union[str, None] = '94ef8270a05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_plan', sa.Column('price', sa.Integer(), nullable=False))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tour_plan', 'price')
    # ### end Alembic commands ###
