"""del inn verif

Revision ID: 4a0e6150da9f
Revises: 0cf01b709de6
Create Date: 2024-02-23 14:09:12.885673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0e6150da9f'
down_revision: Union[str, None] = '0cf01b709de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'inn_verification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('inn_verification', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
