"""add comment to offer

Revision ID: 4f9f8afa01a5
Revises: 568530ce7212
Create Date: 2024-03-14 23:18:17.446714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9f8afa01a5'
down_revision: Union[str, None] = '568530ce7212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_offer', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_offer', 'comment')
    # ### end Alembic commands ###
