"""add tourists into offers

Revision ID: 568530ce7212
Revises: 573c1d689700
Create Date: 2024-03-14 22:26:00.241770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568530ce7212'
down_revision: Union[str, None] = '573c1d689700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_offer', sa.Column('tourAmount', sa.Integer(), nullable=False))
    op.add_column('tour_offer', sa.Column('tourists', sa.JSON(), nullable=False))
    op.drop_column('tour_offer', 'touristsAmount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_offer', sa.Column('touristsAmount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tour_offer', 'tourists')
    op.drop_column('tour_offer', 'tourAmount')
    # ### end Alembic commands ###
