"""test

Revision ID: 61cf704733f0
Revises: 5b1dbc1de0b3
Create Date: 2024-02-12 00:56:13.734702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61cf704733f0'
down_revision: Union[str, None] = '5b1dbc1de0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_schema', sa.Column('recommended_age_from', sa.Integer(), nullable=False))
    op.add_column('tour_schema', sa.Column('recommended_age_to', sa.Integer(), nullable=False))
    op.drop_column('tour_schema', 'recommended_min_age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_schema', sa.Column('recommended_min_age', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tour_schema', 'recommended_age_to')
    op.drop_column('tour_schema', 'recommended_age_from')
    # ### end Alembic commands ###
