"""add touristsAmount to offers

Revision ID: 7ffa3c45c882
Revises: e02eca060497
Create Date: 2024-03-17 23:20:35.280244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ffa3c45c882'
down_revision: Union[str, None] = 'e02eca060497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_offer', sa.Column('touristsAmount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_offer', 'touristsAmount')
    # ### end Alembic commands ###
