"""del isFull

Revision ID: 9bc4d9d99edc
Revises: 3c224523a1ed
Create Date: 2024-03-21 21:34:39.665882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc4d9d99edc'
down_revision: Union[str, None] = '3c224523a1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_plan', 'isFull')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_plan', sa.Column('isFull', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
