"""change tour_schema.id to tourId

Revision ID: ab68ac196800
Revises: 4a0e6150da9f
Create Date: 2024-03-01 00:37:37.644330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab68ac196800'
down_revision: Union[str, None] = '4a0e6150da9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tour_schema', 'id', nullable=False, new_column_name='tourId')
    # ### end Alembic commands ###


# def downgrade() -> None:
    # commands auto generated by Alembic - please adjust! ###
    # op.add_column('tour_schema', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    # op.drop_column('tour_schema', 'tourId')
    # op.drop_constraint(None, 'tour_plan', type_='foreignkey')
    # op.create_foreign_key('tour_plan_schemaId_fkey', 'tour_plan', 'tour_schema', ['schemaId'], ['id'])
    # ### end Alembic commands ###
