"""changeClaimTable

Revision ID: bb35efa8a272
Revises: 49f66e48233c
Create Date: 2024-03-17 14:39:11.582670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb35efa8a272'
down_revision: Union[str, None] = '49f66e48233c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('claimId', sa.Integer(), nullable=False),
    sa.Column('touristId', sa.Integer(), nullable=True),
    sa.Column('gidEmail', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('publicTourId', sa.UUID(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('creationDateTime', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['publicTourId'], ['tour_plan.id'], ),
    sa.ForeignKeyConstraint(['touristId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('claimId')
    )
    op.drop_table('claims')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('claimId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('touristId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gidEmail', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('publicTourId', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('creationDateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['publicTourId'], ['tour_plan.id'], name='claims_publicTourId_fkey'),
    sa.ForeignKeyConstraint(['touristId'], ['user.id'], name='claims_touristId_fkey'),
    sa.PrimaryKeyConstraint('claimId', name='claims_pkey')
    )
    op.drop_table('claim')
    # ### end Alembic commands ###
