"""add isFull

Revision ID: c9e1126bf9dd
Revises: 7ffa3c45c882
Create Date: 2024-03-21 00:42:56.710224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e1126bf9dd'
down_revision: Union[str, None] = '7ffa3c45c882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_plan', sa.Column('isFull', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_plan', 'isFull')
    # ### end Alembic commands ###
