"""renamed default state name for tour plans

Revision ID: da835e277b4c
Revises: ab5ebebf9ec8
Create Date: 2024-03-10 14:23:44.812757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da835e277b4c'
down_revision: Union[str, None] = 'ab5ebebf9ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
