"""deleted payment state from offer

Revision ID: e8547f4d12e2
Revises: 4f9f8afa01a5
Create Date: 2024-03-14 23:23:27.541051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8547f4d12e2'
down_revision: Union[str, None] = '4f9f8afa01a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_offer', 'paymentState')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_offer', sa.Column('paymentState', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
