"""add inn

Revision ID: fb587027b0f4
Revises: 38638c2fd995
Create Date: 2024-02-22 00:51:23.773362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb587027b0f4'
down_revision: Union[str, None] = '38638c2fd995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('inn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'inn')
    # ### end Alembic commands ###
